<div class="footer clearfix mb-0 text-muted">
    <div class="float-start">
        <p>2023 &copy; Intech</p>
    </div>
    <div class="float-end">
        <p>
            Creado por
            <a href="#">Eduardo Aguirrebeña</a>
        </p>
    </div>
</div>
<div id="footerInformation" class="">

    <p>Hello</p>

    <div class="loadingio-spinner-rolling-a4dt90r28kv" id="spinnerBottomContainer">
        <div class="ldio-r2lhg8dn3dg">
            <div></div>
        </div>
    </div>
    
</div>

<style type="text/css"> 
    @keyframes ldio-r2lhg8dn3dg {
        0% {
            transform: translate(-50%, -50%) rotate(0deg);
        }

        100% {
            transform: translate(-50%, -50%) rotate(360deg);
        }
    }

    .ldio-r2lhg8dn3dg div {
        position: absolute;
        width: 40px;
        height: 40px;
        border: 5px solid #e4d8eb;
        border-top-color: #069B99;
        border-radius: 50%;
        /* background-color: linear-gradient(90deg, #36ABA9 0%, #10E5E1 82.29%); */
    }

    .ldio-r2lhg8dn3dg div {
        animation: ldio-r2lhg8dn3dg 0.6896551724137931s linear infinite;
        top: 56.99999999999999px;
        left: 56.99999999999999px;
        /* background-color: linear-gradient(90deg, #36ABA9 0%, #10E5E1 82.29%); */
    }

    .loadingio-spinner-rolling-a4dt90r28kv {
        width: 100px;
        height: 86px;
        display: inline-block;
        overflow: hidden;
    }

    .ldio-r2lhg8dn3dg {
        width: 50px;
        height: 50px;
        position: relative;
        transform: translateZ(0) scale(1);
        backface-visibility: hidden;
        transform-origin: 0 0;
        /* see note above */
    }

    .ldio-r2lhg8dn3dg div {
        box-sizing: content-box;
    }

    /* generated by https://loading.io/ */


   
</style>